# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
r: bioc-release
before_install:
  - curl -OL https://github.com/craigcitro/r-travis/blob/master/scripts/travis-tool.sh
install:
  - ./travis-tool.sh install_bioc graphite
  - ./travis-tool.sh install_bioc graph
  - ./travis-tool.sh install_github JClavel/glassoFast
warnings_are_errors: true
script:
   - R CMD build . --no-resave-data --no-manual
   - R CMD check *tar.gz --as-cran --timings --no-manual